### ISSUE TITLE
Add an update log to the discord 

### ISSUE THREAD

**Issue by ImNotRiley** [TheFoxDen-Network/Factions#28]

**Comment by Fauxxo** [comment]
Can you please let us know what you mean by an update log?

**Comment by ImNotRiley** [comment]
As in, a log of all the updates that occurs, just so we can be up to date on all the features on the server/

**Comment by Fauxxo** [comment]
Oh, definitely! While the current discord server is only a temporary place for the server at the moment, this is definitely a feature I'd like to implement! For the time being, this git-hub repository is the only place where I will be posting updates/changes to the server.
